# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
dist: trusty
sudo: false

cache:
  packages: true
  directories:
    - $HOME/.cache/pip

before_script:
  - export PATH=$HOME/.local/bin:$PATH
  - pip install feather-format pandas --user `whoami`

r_binary_packages:
  - BH
  - dplyr
  - Rcpp
